useDotenv: true
frameworkVersion: '3'

service: medcloud-challange-api

custom:
  tableName: 'patients-table-${sls:stage}'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ PatientsTable, Arn ]
  environment:
    PATIENTS_TABLE: ${self:custom.tableName}
    STAGE: ${sls:stage}

functions:
  patients: 
    handler: handler.handler 
    events: 
      - http: 
          path: patients
          method: post
      - http:
          path: patients
          method: get
      - http:
          path: patients/{id}
          method: get
      - http:
          path: patients/{id}
          method: delete
  

resources:
  Resources:
    PatientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
